server:
  port: 520                                                                     # 端口号
spring:
  application:
    name: Jt-Helper                                                               # 应用名

# datasource----------------------------------------------------------------------------------------------------------
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jt_helper?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234

# redis-----------------------------------------------------------------------------------------------------------------
  data:
    redis:
      host: 127.0.0.1                                                              # redis服务Ip
      port: 6379                                                                   # redis服务连接端口
      password:                                                                   # redis 服务器连接密码(默认为空)
      database: 0                                                                  # redis 数据库号,默认为 0
      connect-timeout: 600000                                                      # 连接超时时间(毫秒) 60 秒
      lettuce:
        pool:
          max-active: 8                                                            # 连接池最大连接数
          max-wait: -1                                                             # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8                                                              # 连接池中的最大空闲连接
          min-idle: 2                                                              # 连接池中的最小空闲连接

# 开启日志 trace<debug<info<warn<error-----------------------------------------------------------------------------------
#logging:
#  level:
#    root: info                                                                         # 顶级日志等级
#    cn.jt: debug                                                                       # 自定义日志等级
#  file:
#    path: logs                                                                         # 日志路径

# mybatis-plus配置------------------------------------------------------------------------------------------------------
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id                                                            # 雪花算法自动生成Id
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl                           # 开启日志

# dozer对象拷贝映射文件---------------------------------------------------------------------------------------------------
dozer:
  mappingFiles:
    - classpath:dozer/dozer-mapping.xml

# 接口文档 knife4j增强配置------------------------------------------------------------------------------------------------
knife4j:
  enable: true
  setting:
    language: zh-CN                               # 文档语言
    swaggerModelName: 实体类列表                   # 重命名SwaggerModel名称,默认
    enable-after-script: false                    # 调试Tab是否显示AfterScript功能,默认开启
#    enable-document-manage: false                 # 是否显示界面中"文档管理"功能
    enable-reload-cache-parameter: true           # 显示刷新变量按钮
    enable-home-custom: true                      # 是否开启自定义主页内容
    home-custom-path: classpath:markdown/home.md  # 主页内容Markdown文件路径
  production: true                               # 生产环境,开启后不可用
  basic:
    enable: true                                  # Basic认证密码
    username: 123                                 # Basic认证用户名
    password: qwe                                 # Basic认证密码
springdoc:
  group-configs:                                  # 文档分组
    - group: '服务文档'                            # 分组名
      packages-to-scan: cn.jt.controller          # 扫描包名
      paths-to-match: '/**'                       # 扫包下所有
  api-docs:
    enabled: true                                 # 是否开启Api文档






